#!/usr/bin/python
import os
os.chdir('/usr/local/neolane/nl6/var/res/malayair_dev/')
for f in os.listdir('/usr/local/neolane/nl6/var/res/malayair_dev/'):
	if os.path.isfile(f):
		file_name, file_ext = os.path.splitext(f)
		f_part, f_date = file_name.split('_')
		new_name = '{}{}'.format(f_part,file_ext)
		os.rename(f, new_name)
